config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'homes/about'
  get '/search', to: 'searchs#search'

  namespace :admin do
    root to: 'books#index'
    resources :books, only: [:show, :destroy]
    resources :customers, only:[:show, :destroy, :index]
    patch 'customers/withdraw/:id', to: 'customers#withdraw'
  end

  namespace :public do
    # ↓いいね、コメント機能
    resources :books, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :customers, only:[:show, :edit, :update, :index] do
      member do
        get :unsubscribe
      end
    end
    patch 'customers/withdraw/:id', to: 'customers#withdraw'
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {registrations: "public/registrations", sessions: 'public/sessions'}

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {sessions: "admin/sessions"}

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  # ↓↓画像
  # ↓↓投稿バリデーション

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy, through: :books
  # いいね機能でのランキング
  has_many :favorited_books, through: :favorites, source: :book

  # バリデーション
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :email, presence: true
  validates :introduction, length: { maximum: 200 }, presence: true
  attachment :profile_image, destroy: false

  # 退会機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    before_action :authenticate_admin!,except: [:new_admin_session_path]

    def index
     @customers = Customer.all
     @customers = Kaminari.paginate_array(@customers).page(params[:page]).per(10)
    end

    def show
   	 @customer = Customer.find(params[:id])
	   end

    def withdraw
     @customer = Customer.find(params[:id])
     @customer.destroy()
     flash[:admin] = "＜不正なユーザーを退会させました。＞"
     redirect_to admin_customers_path
    end

    private

    def customer_params
     params.require(:customer).permit(:is_deleted, :email, :introduction, :name, :profile_image)
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-8 offset-md-1'>
      <h3>＜ユーザー一覧＞</h3>
      <table class='table'>
       <%= flash[:admin] %>
        <thead>
          <tr>
            <th>ユーザー名</th>
            <th>プロフィール画像</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      <%= paginate @customers %>
        <tbody>
          <!--↓↓ユーザー一覧-->
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.name %></td>
              <td><%= attachment_image_tag(customer, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
              <td><%= link_to 'ユーザー詳細', admin_customer_path(customer), class: "customer_#{customer.id}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-8 offset-md-1'>
        <!--↓↓プロフィールの内容-->
        <table class='table'>
          <tr><%= attachment_image_tag(@customer, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
          <tr>
        	  <th>ユーザー名</th>
        	  <th>自己紹介</th>
          </tr>
          <tr>
        	  <th><%= @customer.name %></th>
        	  <th><%= @customer.introduction %></th>
          </tr>
          <tr>
            <%= link_to "退会させますか？", admin_path(@customer.id), method: :PATCH, data: {confirm: "不適切なユーザの退会をします。"}, class: "btn btn-danger" %>
          </tr>
        </table>
    </div>
  </div>
</div>