config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'homes/about'
  get '/search', to: 'searchs#search'

  namespace :admin do
    root to: 'books#index'
    resources :books, only: [:show, :destroy]
    resources :customers, only:[:show, :destroy, :index]
    patch 'customers/withdraw/:id', to: 'customers#withdraw'
  end

  namespace :public do
    # ↓いいね、コメント機能
    resources :books, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :customers, only:[:show, :edit, :update, :index] do
      member do
        get :unsubscribe
      end
    end
    patch 'customers/withdraw/:id', to: 'customers#withdraw'
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {registrations: "public/registrations", sessions: 'public/sessions'}

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {sessions: "admin/sessions"}

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @customer = current_customer
  end
  
  def about
    @customer = current_customer
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 mx-auto text-center">
      <h1 class="my-3" style="font-size:2.5rem;">Las Carasとはスペイン語で顔という意味です。</h1>
      <br>
        <p style="font-size:1.3rem;line-height: 2.5rem;">
          <strong>Las Caras</strong>はあなたの親切を投稿するSNSサイトです。<br>
          普段からあなたが行っている親切を投稿することであなたと世界が変わります。<br>
          <br>
          あなたの親切はポイントで評価され、ランキングで表示されます。<br>
          よって、親切をしてポイントを稼げば、あなたのサイト内での評価が上がり<br>
          就活や就学に活かすことができます。<br>

          さぁ、今すぐ、会員登録をして、徳を重ねましょう。<br>
          <br>
        </p>
          <p style="font-size:0.8rem;line-height: 1.6rem;">
            <%= link_to "Topへ戻る", root_path %>／
            <%= link_to "会員登録", new_customer_registration_path %></p>
            <%= link_to "ログイン", new_customer_session_path %>
          <br>
          <br>
          <p style="font-size:1.0rem;line-height: 2.0rem;">
          （会員ではない方も投稿を見ることはできますが<%= link_to "、",new_admin_session_path %> 投稿とポイント投票には会員登録が必要になります。）
          </p>
      </div>
      <div id="about_visual" class="mx-auto"></div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 mx-auto text-center">
      <br>
      <h1 class="my-4" style="font-size:4.5rem;">Las Caras para sus amigables y sus voluntarios</h1>
      <h1 class="my-3" style="font-size:3.5rem;">あなたの親切が世界を変える</h1>
      <br>
      <br>
      <div class="">
        <%= flash[:destroy] %>
        <p style="font-size:2.0rem;line-height: 3.0rem;">
          <%= link_to "Las Carasについて知りたい", homes_about_path %>／
          <%= link_to "ログインして親切を投稿する", new_customer_session_path %>
        </p>
      <div id="about_visual" class="mx-auto"></div>
    </div>
  </div>
</div>