config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'homes/about'
  get '/search', to: 'searchs#search'

  namespace :admin do
    root to: 'books#index'
    resources :books, only: [:show, :destroy]
    resources :customers, only:[:show, :destroy, :index]
    patch 'customers/withdraw/:id', to: 'customers#withdraw'
  end

  namespace :public do
    # ↓いいね、コメント機能
    resources :books, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :customers, only:[:show, :edit, :update, :index] do
      member do
        get :unsubscribe
      end
    end
    patch 'customers/withdraw/:id', to: 'customers#withdraw'
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {registrations: "public/registrations", sessions: 'public/sessions'}

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {sessions: "admin/sessions"}

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    @customer = current_customer
    # viewのform_tagにて 選択したmodelの値を@modelに代入。
    @model = params["model"]
    # 検索ワードを@contentに代入。
    @content = params["content"]
    # @model, @content,を代入した、# search_forを@recordsに代入。
    @records = search_for(@model, @content)
    @records = Kaminari.paginate_array(@records).page(params[:page]).per(10)
  end

  private
  def search_for(model, content)
     # 選択したモデルがcustomerだったら
    if model == 'customer'
     Customer.where('name LIKE ? OR introduction LIKE ?', '%'+content+'%', '%'+content+'%')
     # 選択したモデルがbookだったら
    elsif model == 'book'
     Book.where('title LIKE ? OR place LIKE ? OR explanation LIKE ?', '%'+content+'%', '%'+content+'%', '%'+content+'%')
    end
  end
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searchs/search.html.erb
<div class ='container'>
  <div class='row'>
    <div class='col-md-8 offset-md-1'>
        <% if @model == 'customer' %>
          <h4>【登録者の検索結果】検索ワード：<%= @content %></h4>
          <table class='table table-hover table-inverse'>
            <thead>
              <tr>
                <th>ユーザー名</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <%= paginate @records %>
            <tbody>
              <% @records.each do |customer| %>
                <tr>
                  <td><%= customer.name %></td>
                  <td>
                  <% if customer_signed_in? %>
                  <%= link_to 'ユーザー詳細', public_customer_path(customer), class: "customer_#{customer.id}" %>
                  <% end %>
                  </td>
                  <td>
                  <% if admin_signed_in? %>
                  <%= link_to 'ユーザー詳細', admin_customer_path(customer), class: "customer_#{customer.id}" %>
              　　<% end %>
                  </td>
                </tr>
      　　　　　  <% end %>
            </tbody>
          </table>
            <%= paginate @records %>

        <% else @model == 'book' %>
          <h4>【投稿の検索結果】検索ワード：<%= @content %></h4>
          <table class='table table-hover table-inverse'>
            <thead>
              <tr>
                <th>活動タイトル</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <%= paginate @records %>
            <tbody>
              <% @records.each do |book| %>
                <tr>
                  <td><%= book.title %></td>
                  <td><% if customer_signed_in? %>
                  <%= link_to '投稿の詳細', public_book_path(book), class: "book_#{book.id}" %>
                  <% end %>
                  </td>
                  <td>
                  <% if admin_signed_in? %>
                  <%= link_to '投稿の詳細', admin_book_path(book), class: "customer_#{book.id}" %>
                  <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
            <%= paginate @records %>
        <% end %>
    </div>
  </div>
</div>