config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'homes/about'
  get '/search', to: 'searchs#search'

  namespace :admin do
    root to: 'books#index'
    resources :books, only: [:show, :destroy]
    resources :customers, only:[:show, :destroy, :index]
    patch 'customers/withdraw/:id', to: 'customers#withdraw'
  end

  namespace :public do
    # ↓いいね、コメント機能
    resources :books, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :customers, only:[:show, :edit, :update, :index] do
      member do
        get :unsubscribe
      end
    end
    patch 'customers/withdraw/:id', to: 'customers#withdraw'
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {registrations: "public/registrations", sessions: 'public/sessions'}

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {sessions: "admin/sessions"}

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :customer
  attachment :image
  has_many :favorites, dependent: :destroy
  has_many :favorited_customers, through: :favorites, source: :customer
  has_many :book_comments, dependent: :destroy
  has_many :tags, dependent: :destroy

  validates :title, presence: true, length: { maximum: 15 }
  validates :place, presence: true, length: { maximum: 10 }
  validates :explanation, presence: true, length: { maximum: 50 }
  
  validates :image, presence: true


  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :customer
    belongs_to :book
    validates :comment, presence: true, length: { maximum: 200 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  # ↓↓画像
  # ↓↓投稿バリデーション

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy, through: :books
  # いいね機能でのランキング
  has_many :favorited_books, through: :favorites, source: :book

  # バリデーション
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :email, presence: true
  validates :introduction, length: { maximum: 200 }, presence: true
  attachment :profile_image, destroy: false

  # 退会機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
  belongs_to :customer
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :customer_id
    
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :book
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
    before_action :authenticate_admin!
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :authenticate_admin!,except: [:new_admin_session_path]

  def show
    @book = Book.find(params[:id])
  end

  def index
  #   # 投稿したものを表示する。
    @books = Book.all
    @books = Kaminari.paginate_array(@books).page(params[:page]).per(10)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:admin] = "＜不正な投稿を削除しました。＞"
    redirect_to admin_root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :place, :explanation, :image)
  end


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    before_action :authenticate_admin!,except: [:new_admin_session_path]

    def index
     @customers = Customer.all
     @customers = Kaminari.paginate_array(@customers).page(params[:page]).per(10)
    end

    def show
   	 @customer = Customer.find(params[:id])
	   end

    def withdraw
     @customer = Customer.find(params[:id])
     @customer.destroy()
     flash[:admin] = "＜不正なユーザーを退会させました。＞"
     redirect_to admin_customers_path
    end

    private

    def customer_params
     params.require(:customer).permit(:is_deleted, :email, :introduction, :name, :profile_image)
    end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_in_path_for(resource)
    admin_root_path
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :authenticate_customer!,except: [:index]

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:profile_image_id,:email,:introduction, :is_deleted])
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @customer = current_customer
  end
  
  def about
    @customer = current_customer
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    @customer = current_customer
    # viewのform_tagにて 選択したmodelの値を@modelに代入。
    @model = params["model"]
    # 検索ワードを@contentに代入。
    @content = params["content"]
    # @model, @content,を代入した、# search_forを@recordsに代入。
    @records = search_for(@model, @content)
    @records = Kaminari.paginate_array(@records).page(params[:page]).per(10)
  end

  private
  def search_for(model, content)
     # 選択したモデルがcustomerだったら
    if model == 'customer'
     Customer.where('name LIKE ? OR introduction LIKE ?', '%'+content+'%', '%'+content+'%')
     # 選択したモデルがbookだったら
    elsif model == 'book'
     Book.where('title LIKE ? OR place LIKE ? OR explanation LIKE ?', '%'+content+'%', '%'+content+'%', '%'+content+'%')
    end
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_signed.html.erb
<li class="nav-item">
  <%= link_to "投稿一覧", admin_root_path, class:"nav-link ml-4" %>
</li>
<li class="nav-item">
  <%= link_to "ユーザー一覧", admin_customers_path, class:"nav-link ml-4" %>
</li>
<li class="nav-item">
  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"nav-link ml-4" %>
</li>
<div class='nav-bar'>
<%= form_tag(search_path, method: :get) do %>
<%= text_field_tag 'content' %>
<%= select_tag 'model', options_for_select({ "登録者を検索" => "customer", "投稿を検索" => "book" }) %>
<%= submit_tag 'Buscar' %>
<% end %>
</div>

app/views/layouts/_customer_signed.html.erb
<!--ログイン後の画面-->
<li class="nav-item">
  <%= link_to "マイページ", public_customer_path(@customer), class:"nav-link ml-2" %>
</li>
<li class="nav-item">
  <%= link_to "投稿一覧", public_books_path, class:"nav-link ml-2" %>
</li>
<li class="nav-item">
  <%= link_to "登録一覧", public_customers_path, class:"nav-link ml-2" %>
</li>
<li class="nav-item">
  <%= link_to "新規投稿", new_public_book_path, class:"nav-link ml-2" %>
</li>
<li class="nav-item">
  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"nav-link ml-2" %>
</li>
<div class='nav-bar'>
<%= form_tag(search_path, method: :get) do %>
<%= text_field_tag 'content' %>
<%= select_tag 'model', options_for_select({ "登録者を検索" => "customer", "投稿を検索" => "book" }) %>
<%= submit_tag 'Buscar' %>
<% end %>
</div>

app/views/layouts/_error.html.erb
<% if model.errors.any? %>
  <div class = "error">
     <ul>
        <% model.errors.full_messages.each do |message| %>
           <li><%= message %></li>
	    <% end %>
     </ul>
  </div>
<% end %>

app/views/layouts/_no_signed.html.erb
<li class="nav-item">
  <%= link_to "登録一覧", public_customers_path, class:"nav-link ml-2" %>
</li>
<li class="nav-item">
  <%= link_to "投稿一覧", public_books_path, class:"nav-link ml-2" %>
</li>
<li class="nav-item">
  <%= link_to "新規登録", new_customer_registration_path, class:"nav-link ml-2" %>
</li>
<li class="nav-item">
  <%= link_to "ログイン", customer_session_path, class:"nav-link ml-2" %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Las Caras</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <div class="col-3">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse flex-column small" id="navbarNavDropdown">
                  <% if customer_signed_in? %>
                    <span>ようこそ、<%= current_customer.name %> さん！</span>
                  <% end %>
                  <ul class="navbar-nav d-flex flex-wrap">
                    <% if customer_signed_in? %>
                    <%= render "layouts/customer_signed" %>
                    <% elsif admin_signed_in? %>
                    <%= render 'layouts/admin_signed' %>
                    <% else %>
                    <%= render 'layouts/no_signed' %>
                    <% end %>
                  </ul>
              </div>
            </div>
            <div class="col-6 text-center">
              <%= link_to "", root_path, class:"navbar-brand" %>
            </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer class="text-center my-3">
      <%= link_to "©Las Caras - sattaku1538", root_path %>
    </footer>
  </body>
</html>